import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type ConditionTypeDef = {
    alias: string;
    type: string;
    fields: Array<{ name: string; typeText: string }>;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const conditionsPath = path.resolve(repoRoot, "../language/src/types/conditions.ts");
const outputPath = path.resolve(repoRoot, "src/importer/conditionMappings.generated.ts");

function guessKind(fieldName: string, typeText: string): string {
    const normalized = typeText.replace(/\s+/g, " ").trim();

    if (fieldName === "itemName") return "item";
    if (normalized === "string") return "value";
    if (normalized === "boolean") return "boolean";
    if (normalized === "number") return "value";

    if (
        [
            "Comparison",
            "Gamemode",
            "Permission",
            "PotionEffect",
            "ItemProperty",
            "ItemLocation",
            "ItemAmount",
            "VarHolder",
        ].some((name) => normalized.includes(name))
    ) {
        return "select";
    }

    if (normalized.includes("Value")) {
        return "value";
    }

    return "value";
}

function parseConditionTypeDefs(source: string): ConditionTypeDef[] {
    const defs: ConditionTypeDef[] = [];
    const typeBlockRegex = /export type (Condition\w+) = \{([\s\S]*?)\n\};/g;

    for (const match of source.matchAll(typeBlockRegex)) {
        const [, alias, body] = match;
        const fieldMatches = [...body.matchAll(/^\s*(\w+)\??:\s*([^;]+);$/gm)];
        const typeField = fieldMatches.find((field) => field[1] === "type");
        if (!typeField) continue;

        const typeLiteral = typeField[2].match(/^"([A-Z_]+)"$/)?.[1];
        if (!typeLiteral) continue;

        const fields = fieldMatches
            .filter(([_, name]) => !["type", "inverted", "note"].includes(name))
            .map(([_, name, typeText]) => ({
                name,
                typeText: typeText.trim(),
            }));

        defs.push({
            alias,
            type: typeLiteral,
            fields,
        });
    }

    return defs;
}

function renderMappingEntry(def: ConditionTypeDef): string {
    const fieldLines = def.fields.map(
        (field) =>
            `            "TODO ${field.name}": { prop: "${field.name}", kind: "${guessKind(field.name, field.typeText)}" },`
    );

    return [
        `    ${def.type}: {`,
        `        loreFields: {`,
        ...(fieldLines.length > 0 ? fieldLines : []),
        `        },`,
        `    },`,
    ].join("\n");
}

async function main(): Promise<void> {
    const source = await readFile(conditionsPath, "utf8");
    const defs = parseConditionTypeDefs(source);

    const renderedEntries = defs.map(renderMappingEntry).join("\n\n");

    const output = `import type { Condition } from \"htsw/types\";\n\nimport type { ConditionLoreSpec } from \"./types\";\n\n// Generated by scripts/generateConditionMappingScaffold.ts\n// Safe to regenerate. Copy pieces from here into conditionMappings.ts as needed.\nexport const CONDITION_LORE_MAPPINGS_SCAFFOLD = {\n${renderedEntries}\n} satisfies {\n    [K in Condition[\"type\"]]?: ConditionLoreSpec<\n        Extract<Condition, { type: K }>\n    >;\n};\n`;

    await writeFile(outputPath, output, "utf8");
    console.log(`Wrote ${path.relative(process.cwd(), outputPath)}`);
}

await main();
