#!/usr/bin/env node
// Embeds two doc sets into the CLI bundle as src/generated/guides.ts:
//   - agents/ + housing/ from HTSW_DOCS_PATH (the private LGHousing/docs repo)
//   - this repo's own docs/ (the HTSW language reference) under htsw/
// With HTSW_DOCS_PATH unset the guide set is empty except for htsw/ docs, so
// `htsw check` / `htsw run` still build; `htsw agents install` reports the
// build carries no guides only when nothing embedded at all.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(here, "..", "src", "generated");
const outFile = path.join(outDir, "guides.ts");
const htswDocsDir = path.join(here, "..", "..", "docs");

const GUIDE_DIRS = ["agents", "housing"];

function walk(dir, root, files) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            walk(full, root, files);
        } else if (entry.isFile() && entry.name.endsWith(".md")) {
            const rel = path.relative(root, full).split(path.sep).join("/");
            files[rel] = fs.readFileSync(full, "utf8");
        }
    }
}

function collect(root) {
    const files = {};
    for (const dir of GUIDE_DIRS) {
        const base = path.join(root, dir);
        if (fs.existsSync(base)) walk(base, root, files);
    }
    return files;
}

// mdBook hides lines that start with the hideline prefix (`~` for htsl/json
// here) inside a code fence — they are playground wrapper boilerplate, not part
// of the reading. Strip them so the embedded plain-text docs match the site.
function stripHidelines(md) {
    const out = [];
    let inFence = false;
    for (const line of md.split("\n")) {
        if (line.trimStart().startsWith("```")) {
            inFence = !inFence;
            out.push(line);
        } else if (inFence && line.startsWith("~") && !line.startsWith("~~~")) {
            continue;
        } else {
            out.push(line);
        }
    }
    return out.join("\n");
}

function collectHtswDocs(baseDir) {
    const raw = {};
    if (fs.existsSync(baseDir)) walk(baseDir, baseDir, raw);
    const out = {};
    for (const key of Object.keys(raw)) out[`htsw/${key}`] = stripHidelines(raw[key]);
    return out;
}

function docsVersion(root) {
    try {
        return execFileSync("git", ["-C", root, "rev-parse", "--short", "HEAD"], {
            encoding: "utf8",
        }).trim();
    } catch {
        return "unknown";
    }
}

const docsPath = process.env.HTSW_DOCS_PATH;
let files = {};
let version = "none";
if (docsPath && fs.existsSync(docsPath)) {
    files = collect(docsPath);
    version = docsVersion(docsPath);
} else {
    console.warn("[embed-guides] HTSW_DOCS_PATH unset or missing; embedding no agents/housing guides");
}

const htswDocs = collectHtswDocs(htswDocsDir);
Object.assign(files, htswDocs);

const sorted = {};
for (const key of Object.keys(files).sort()) sorted[key] = files[key];

console.log(
    `[embed-guides] embedded ${Object.keys(sorted).length} files ` +
    `(${Object.keys(htswDocs).length} from docs/) @ ${version}`
);

const body =
    "// Generated by scripts/embed-guides.mjs. Do not edit by hand.\n" +
    `export const GUIDE_SOURCE_VERSION = ${JSON.stringify(version)};\n` +
    `export const GUIDES: Record<string, string> = ${JSON.stringify(sorted, null, 2)};\n`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, body);
