#!/usr/bin/env node
// Embeds the private LGHousing/docs agents/ + housing/ guides into the CLI
// bundle as src/generated/guides.ts. Source path comes from HTSW_DOCS_PATH.
// With HTSW_DOCS_PATH unset, emits an empty set so `htsw check` / `htsw run`
// still build; `htsw agents install` then reports the build carries no guides.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(here, "..", "src", "generated");
const outFile = path.join(outDir, "guides.ts");

const GUIDE_DIRS = ["agents", "housing"];

function walk(dir, root, files) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            walk(full, root, files);
        } else if (entry.isFile() && entry.name.endsWith(".md")) {
            const rel = path.relative(root, full).split(path.sep).join("/");
            files[rel] = fs.readFileSync(full, "utf8");
        }
    }
}

function collect(root) {
    const files = {};
    for (const dir of GUIDE_DIRS) {
        const base = path.join(root, dir);
        if (fs.existsSync(base)) walk(base, root, files);
    }
    const sorted = {};
    for (const key of Object.keys(files).sort()) sorted[key] = files[key];
    return sorted;
}

function docsVersion(root) {
    try {
        return execFileSync("git", ["-C", root, "rev-parse", "--short", "HEAD"], {
            encoding: "utf8",
        }).trim();
    } catch {
        return "unknown";
    }
}

const docsPath = process.env.HTSW_DOCS_PATH;
let files = {};
let version = "none";
if (docsPath && fs.existsSync(docsPath)) {
    files = collect(docsPath);
    version = docsVersion(docsPath);
    console.log(`[embed-guides] embedded ${Object.keys(files).length} files from ${docsPath} @ ${version}`);
} else {
    console.warn("[embed-guides] HTSW_DOCS_PATH unset or missing; embedding no guides");
}

const body =
    "// Generated by scripts/embed-guides.mjs. Do not edit by hand.\n" +
    `export const GUIDE_SOURCE_VERSION = ${JSON.stringify(version)};\n` +
    `export const GUIDES: Record<string, string> = ${JSON.stringify(files, null, 2)};\n`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, body);
