[book]
title = "HTSW Documentation"
authors = ["sndyx", "callanftw", "j_sse"]
language = "en"
src = "."

[build]
build-dir = "../book"

[output.html]
git-repository-url = "https://github.com/LGHousing/htsw"
edit-url-template = "https://github.com/LGHousing/htsw/edit/main/docs/{path}"
site-url = "/htsw/"
theme = "theme"
additional-js = ["htsw-playground-runner.bundle.js", "theme/htsl-playground.js"]

[output.html.playground]
runnable = true

[output.html.code.hidelines]
htsl = "~"
json = "~"
